CREATE TABLE Persona(
	id INT PRIMARY KEY AUTO_INCREMENTAL,
  nombre VARCHAR(255),
  apellidos VARCHAR(255)
);

CREATE TABLE Alumno(
	id INT PRIMARY KEY AUTO_INCREMENTAL,
  DNINIA VARCHAR(15),
	id_persona 
);
CREATE TABLE Profesor(
	id INT PRIMARY KEY AUTO_INCREMENTAL,
  asignaturas SET
);